[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@ds-test/=lib/forge-std/lib/ds-test/src/",
  "@forge-std/=lib/forge-std/src/",
  "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
  "@layerzerolabs/lz-evm-v1-0.7/=lib/LayerZero/",
  "solidity-bytes-utils/=lib/solidity-bytes-utils/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
